{
    "description": "Verify PollTimeLimitReached exception is raised when polling function that returns a falsy and timeout is 0.01 sec",
    "input": {
        "lambda_function": "lambda: False",
        "poll_kwargs": {
            "args": [],
            "step_fun": "step_constant",
            "step_fun_kwargs": {
                "step": 0.01
            },
            "timeout": 0.01
        }
    },
    "expected_output": {
        "error": {
            "type": "PollTimeLimitReached",
            "message": "Poll was not successful in time limit (0.01 seconds)"
        }
    }
}